# For more information see:
#  * https://docs.github.com/en/actions/learn-github-actions
#  * https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#  * https://github.com/actions/setup-java/blob/v3.13.0/docs/advanced-usage.md#Publishing-using-Apache-Maven
#

name: Deployment workflow

on:
    release:
      types: [published]
  
jobs:
  # old-school build and jar method. No tests run or compiled.
  publish-1_6: 
    name: Publish Java 1.6 to GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.6
      - name: Compile Java 1.6
        run: |
          mkdir -p target/classes
          javac -version
          javac -source 1.6 -target 1.6 -d target/classes/ src/main/java/org/json/*.java
      - name: Create JAR 1.6
        run: |
          jar cvf "target/org.json-1.6-${{ github.ref_name }}.jar" -C target/classes .
      - name: Add 1.6 Jar To Release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            target/*.jar
  publish:
    name: Publish Java 8 to Maven Central and GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          # Use lowest supported LTS Java version
          java-version: '8'
          distribution: 'temurin'
          server-id: ossrh  # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
  
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          
      - name: Add Jar To Release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            target/*.jar
      # - name: Set up Java for publishing to GitHub Packages
      #   uses: actions/setup-java@v3
      #   with:
      #     # Use lowest supported LTS Java version
      #     java-version: '8'
      #     distribution: 'temurin'
      # - name: Publish to GitHub Packages
      #   run: mvn --batch-mode deploy
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
